'use server'

import { prisma } from '@/lib/prisma'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { sendEmail } from '@/lib/email'
import { auth } from '@/auth'

const TicketSchema = z.object({
    title: z.string().min(5),
    description: z.string().min(10),
    priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']),
    location: z.string().optional(),
})

export async function createTicket(prevState: any, formData: FormData) {
    const session = await auth()
    if (!session?.user?.id) return { error: 'Unauthorized' }

    // Fetch user to get departmentId
    const user = await prisma.user.findUnique({ where: { id: session.user.id } })
    if (!user) return { error: 'User not found' }

    const data = {
        title: formData.get('title') as string,
        description: formData.get('description') as string,
        priority: formData.get('priority') as any,
        location: formData.get('location') as string,
        departmentId: formData.get('departmentId') as string,
    }

    const validated = TicketSchema.extend({
        departmentId: z.string().min(1)
    }).safeParse(data)

    if (!validated.success) return { error: 'Invalid data' }

    try {
        const ticket = await prisma.ticket.create({
            data: {
                ...validated.data,
                requesterId: user.id,
                // departmentId is now in validated.data
                status: 'OPEN',
                // uuid is auto-generated by @default(uuid()) in schema
            }
        })

        await prisma.auditLog.create({
            data: {
                action: 'TICKET_CREATED',
                userId: session.user.id,
                ticketId: ticket.id,
                details: `Ticket created: ${ticket.title}`
            }
        })

        revalidatePath('/requester')
        return { success: true }
    } catch (e) {
        console.error(e)
        return { error: 'Failed to create ticket' }
    }
}

export async function assignTicket(ticketId: string, technicianId: string) {
    const session = await auth()
    // Authorization check omitted for brevity (should check Manager role)

    try {
        const ticket = await prisma.ticket.update({
            where: { id: ticketId },
            data: {
                technicianId,
                status: 'ASSIGNED',
            },
            include: { technician: true }
        })

        await prisma.auditLog.create({
            data: {
                action: 'TICKET_ASSIGNED',
                userId: session?.user?.id || 'system',
                ticketId: ticket.id,
                details: `Assigned to ${ticket.technician?.name}`
            }
        })

        // Send Email
        if (ticket.technician?.email) {
            await sendEmail({
                to: ticket.technician.email,
                subject: `New Assignment: ${ticket.title}`,
                html: `<p>You have been assigned ticket #${ticket.uuid}.</p>`
            })
        }

        revalidatePath('/manager')
        return { success: true }
    } catch (e) {
        return { error: 'Failed to assign ticket' }
    }
}

export async function requestOTP(ticketId: string) {
    const session = await auth()
    // Check technician permissions?

    const otp = Math.floor(100000 + Math.random() * 900000).toString()
    const expiresAt = new Date(Date.now() + 15 * 60 * 1000) // 15 mins

    try {
        const ticket = await prisma.ticket.update({
            where: { id: ticketId },
            data: {
                otp,
                otpExpiresAt: expiresAt,
                status: 'RESOLVED' // Pending verification
            },
            include: { requester: true }
        })

        // Audit Log
        await prisma.auditLog.create({
            data: {
                action: 'OTP_REQUESTED',
                userId: session?.user?.id || 'system',
                ticketId: ticket.id,
                details: 'Technician requested OTP for completion'
            }
        })

        // Send Email to Requester
        if (ticket.requester.email) {
            await sendEmail({
                to: ticket.requester.email,
                subject: `Completion OTP for Ticket #${ticket.uuid || ticket.id}`,
                html: `
                    <h3>Ticket Completion Verification</h3>
                    <p>Technician has completed the work for ticket <strong>${ticket.title}</strong>.</p>
                    <p>Please provide this OTP to the technician to close the ticket:</p>
                    <h2 style="font-size: 24px; letter-spacing: 5px;">${otp}</h2>
                `
            })
        }

        revalidatePath('/technician')
        return { success: true }
    } catch (e) {
        return { error: 'Failed to generate OTP' }
    }
}

export async function verifyOTP(ticketId: string, code: string) {
    const session = await auth()

    try {
        const ticket = await prisma.ticket.findUnique({ where: { id: ticketId } })
        if (!ticket) return { error: 'Ticket not found' }

        if (ticket.otp !== code) {
            return { error: 'Invalid OTP' }
        }

        if (!ticket.otpExpiresAt || new Date() > ticket.otpExpiresAt) {
            return { error: 'OTP Expired' }
        }

        // Close Ticket
        await prisma.ticket.update({
            where: { id: ticketId },
            data: {
                status: 'CLOSED',
                otp: null, // clear it
                otpExpiresAt: null
            }
        })

        await prisma.auditLog.create({
            data: {
                action: 'TICKET_CLOSED',
                userId: session?.user?.id || 'system',
                ticketId: ticket.id,
                details: 'Ticket closed via valid OTP'
            }
        })

        revalidatePath('/technician')
        return { success: true }

    } catch (e) {
        return { error: 'Verification failed' }
    }
}
